config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions'
  }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'cards/new'
  get 'cards/create'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'addresses', to: 'users/registrations#create_address'
    # patch 'users', to: 'users/registrations#update'
    # patch 'addresses', to: 'users/registrations#address_update'
  end
  root to: 'orders#index'
  resources :orders, only: [:new, :create]
  get 'orders/select_address', to: 'orders#select_address'
  post 'order/add_address', to: 'orders#add_address'
  post 'orders/comfimation', to: 'orders#add_address'
  get 'orders/comfimation', to: 'orders#comfimation'
  resources :users, only: [:show, :edit]
  resources :cards, only: [:new, :create]
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_one :address

  with_options presence: true do
    validates :k_name
    validates :r_name
    validates :birthday
    validates :height
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @user = current_user
  end

  def new
    if user_signed_in?
      @order = Order.new
    else
      redirect_to new_user_registration_path
    end
  end

  def create
    @order = Order.new(order_params)
    unless @order.valid?
      render :new and return
    end
    session["order_data"] = {order: @order.attributes}
    session["user_data"] = {user: current_user.attributes}
    redirect_to orders_select_address_path

    # NeworderMailer.send_mail.deliver_now
  end

  def select_address
    @user = User.find(current_user.id)
    @address = @user.address
  end

  def add_address
    @address = Address.new(address_params)
    unless @address.valid?
      render :select_address and return
    end
    session["address_data"] = {new_address: @address.attributes}
    redirect_to orders_comfimation_path
  end

  def comfimation
    @address = current_user.address
    if session["address_data"].present?
      @new_address = Address.new(session["address_data"]["new_address"])
    end
    @order = Order.new(session["order_data"]["order"])
  end

  private

  def order_params
    params.require(:order).permit(:k_name,:r_name,:birthday,:height).merge(user_id: current_user.id)
  end

  def address_params
    params.require(:address).permit(:postcode,:prefecture,:city,:street,:building,:first_name, :first_name_kana, :last_name, :last_name_kana, :tel).merge(user_id: current_user.id)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/comfimation.html.erb
<div class="comfimation">
  <div class="container">
    <p class="title">
      ご注文内容の確認
    </p>
    <div class="order_data">
      <div class="order_baby">
      <p class="sub_title">
        赤ちゃんのこと
      </p>
        <ul>
          <li><%= @order.k_name %><br></li>
          <li><%= @order.r_name %><br></li>
          <li><%= @order.birthday %><br></li>
          <li><%= @order.height %>cm<br></li>
        </ul>
      </div>

      <div class="order_address">
      <p class="sub_title">
        配送先
      </p>
        <% if @new_address.blank? %>
        <ul>
          <li class="name"><%= current_user.first_name %><%= current_user.last_name %><br /></li>
          <li class="postcode">〒<%= @address.postcode %><br /></li>
          <li class="address"><%= @address.prefecture_name %><%= @address.city%><br /></li>
          <li><%= @address.street %></li>
          <li><%= @address.building %></li>
        </ul>
        <% elsif @new_address.postcode.present? %>
        <ul>
          <li class="name"><%= @new_address.first_name %><%= @new_address.last_name %><br /></li>
          <li class="postcode">〒<%= @new_address.postcode %><br /></li>
          <li class="address"><%= @new_address.prefecture_name %><%= @new_address.city%><br /></li>
          <li><%= @new_address.street %></li>
          <li><%= @new_address.building %></li>
        </ul>
        <% else %>
      <ul>
          <li class="name"><%= current_user.first_name %><%= current_user.last_name %><br /></li>
          <li class="postcode">〒<%= @address.postcode %><br /></li>
          <li class="address"><%= @address.prefecture_name %><%= @address.city%><br /></li>
          <li><%= @address.street %></li>
          <li><%= @address.building %></li>
        </ul>
        <% end %>
      </div>
    </div>

       <%# <div class="btn next"> %>
        <%= link_to cards_new_path do %>
        <div class="sc-eTpRJs cegJMn-second">
        <div class="sc-iuJeZd bJmZck-second">
          <div class="sc-esOvli imkpqd-second">支払いへ進む<br></div>
        </div>
    <% end %>
    </div>
  </div>
<%# </div> %>

</div>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/select_address.html.erb
<%= render 'shared/header' %>
<div class="send_address" >

    <p class="title">配送先の選択</p>
    <div class="select_address" id="select_address">
      <p class="sub_title">選択中の配送先</p>
      <div class="address_list">
        <ul>
          <li class="name"><%= @address.first_name %><%= @address.last_name %><br /></li>
          <li class="postcode">〒<%= @address.postcode %><br /></li>
          <li class="address"><%= @address.prefecture_name %><%= @address.city%><%= @address.street %><br /></li>
          <li><%= @address.building %></li>
        </ul>
      </div>
    </div>
    <div class="new_address" id="new_address">
      <span class="add_address"  id="add_address">
        【違う配送先を指定】
      <svg width="18" height="13" fill="cadetblue" fill-rule="evenodd" viewBox="0 0 24 24" aria-hidden="true"><path d="M17.51,11.3H12.7v-5a.7.7,0,0,0-1.4,0v5h-5a.7.7,0,0,0,0,1.4h5v4.81a.7.7,0,0,0,1.4,0V12.7h4.81a.7.7,0,0,0,0-1.4Z"></path><path d="M12,2A10,10,0,1,0,22,12,10,10,0,0,0,12,2Zm0,18.6A8.6,8.6,0,1,1,20.6,12,8.61,8.61,0,0,1,12,20.6Z"></path></svg></span>
    </div>

    <div class="address_form hidden" id="address_form" >
      <%= form_with model: Address.new, url: orders_comfimation_path, id: "form", local: true do |f| %>

      <div class="field">
        <%= f.label :お名前 %><br />
        <%= f.text_field :first_name, placeholder:"例）伊藤" %>
        <%= f.text_field :last_name,  placeholder:"例）健太郎" %>
      </div>

      <div class="field">
        <%= f.label :お名前カナ %><br />
        <%= f.text_field :first_name_kana, placeholder:"例）イトウ" %>
        <%= f.text_field :last_name_kana, placeholder:"例）ケンタロウ" %>
      </div>

      <div class="field">
        <%= f.label :電話番号 %><i>（ハイフン不要）</i><br />
        <%= f.text_field :tel %>
      </div>

      <div class="field">
        <%= f.label :postcode, '郵便番号' %><br />
        <%= f.text_field :postcode, autocomplete:'postcode', id:'user_postcode' %>
      </div>

      <div class="field">
        <%= f.label :prefecture, "都道府県" %><br />
        <%= f.collection_select(:prefecture, JpPrefecture::Prefecture.all, :name, :name, { prompt: '選択してください' }, id:'user_prefecture_code') %>
      </div>

      <div class="field">
        <%= f.label :city, '市区町村' %><br />
        <%= f.text_field :city, autocomplete: 'address_city', id:'user_address_city' %>
      </div>

      <div class="field">
        <%= f.label :street, '番地' %><br />
        <%= f.text_field :street, autocomplete: 'address_street', id:'user_address_street' %>
      </div>

      <div class="field">
        <%= f.label :building, '建物名・号室' %><br />
        <%= f.text_field :building, autocomplete: 'address_building', id:'user_address_building' %>
      </div>

      <div class="btn btn--orange btn--circle btn--circle-a btn--shadow">
        <%= f.submit 'こちらの配送先に送る', id: "submit" %>
      </div>
      <% end %>
    </div>

    <a href="/orders/comfimation" class="btn btn--orange btn--circle btn--circle-a btn--shadow">次へ進む</a>

</div>